runtime: java21

env_variables:
  MONGODB_URI: "mongodburi"
  MONGODB_NAME: "mongodbname"
  JWT_SECRET: "jwtsecret"
  COGNITO_ISSUER_URI: "cognitouri"
  COGNITO_CLIENT_ID: "cognitoclient"
  AWS_ACCESS_KEY_ID: "awskey"
  AWS_SECRET_ACCESS_KEY: "awssecret"
  AWS_REGION: "awsregion"
