steps:
  - name: maven:3.9.2-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'test' ]
  - name: maven:3.9.2-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag2', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag2' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['echo', '$MONGODB_URI']
    secretEnv: [ 'MONGODB_URI' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ 'echo', '$$MONGODB_URI' ]
    secretEnv: [ 'MONGODB_URI' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [ 'run', 'deploy', 'google-appengine',
            '--image', 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag2',
            '--region', 'us-central1',
            '--set-env-vars', 'SPRING_DATA_MONGODB_URI=$MONGODB_URI' ]
    secretEnv: [ 'MONGODB_URI' ]
    timeout: '1600s'
images:
  - 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag2'
availableSecrets:
  secretManager:
    - versionName: projects/826713720386/secrets/MONGODB_URI/versions/1
      env: 'MONGODB_URI'