steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo $$MONGODB_URI
    secretEnv: [ 'MONGODB_URI' ]
  - name: 'ubuntu'
    env:
      - 'BAR=$$MONGODB_URI'
    script: 'echo $BAR'
    secretEnv: [ 'MONGODB_URI' ]
availableSecrets:
  secretManager:
    - versionName: projects/fherdelpino/secrets/MONGODB_URI/versions/3
      env: 'MONGODB_URI'