steps:
  - name: 'bash'
    args: [ 'echo', '$$MONGODB_URI' ]
    secretEnv: [ 'MONGODB_URI' ]
  - name: 'bash'
    args: [ 'echo', '$$MONGODB_URI2' ]
    secretEnv: [ 'MONGODB_URI2' ]
availableSecrets:
  secretManager:
    - versionName: projects/826713720386/secrets/MONGODB_URI/versions/3
      env: 'MONGODB_URI'
    - versionName: projects/fherdelpino/secrets/MONGODB_URI/versions/3
      env: 'MONGODB_URI2'