steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'echo $$MONGODB_URI' ]
    secretEnv: [ 'MONGODB_URI' ]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'echo $$MONGODB_URI2' ]
    secretEnv: [ 'MONGODB_URI2' ]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/fherdelpino/secrets/MONGODB_URI/versions/3
      env: 'MONGODB_URI2'