steps:
  - name: maven:3.9.2-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'test' ]
  - name: maven:3.9.2-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag2', '.' ]
    secretEnv: [ 'SPRING_DATA_MONGODB_URI' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]
    timeout: '1600s'
images:
  - 'us-central1-docker.pkg.dev/fherdelpino/cloud-run-source-deploy/appengine-docker-img:tag1'
availableSecrets:
  secretManager:
    - versionName: projects/826713720386/secrets/MONGODB_URI/versions/1
      env: 'SPRING_DATA_MONGODB_URI'