steps:
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'test' ]
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appengine-docker-img:${_DOCKER_IMG_TAG}', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appengine-docker-img:${_DOCKER_IMG_TAG}' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud run deploy google-appengine --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appengine-docker-img:${_DOCKER_IMG_TAG} --region $LOCATION --allow-unauthenticated --set-env-vars SPRING_DATA_MONGODB_URI=$$MONGODB_URI,JWT_SECRET=$$JWT_SECRET' ]
    secretEnv: [ 'MONGODB_URI', 'JWT_SECRET' ]
    timeout: '1600s'
substitutions:
  _DOCKER_IMG_TAG: tag5
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appengine-docker-img:${_DOCKER_IMG_TAG}'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'