version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
    external: true